# docker-compose.yml (scoped to recreacion_linux/)
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dropi-inter:latest
    working_dir: /app
    user: "pwuser"
    # Compose reads .env on the host (same dir as this file) and injects variables
    env_file:
      - .env
    environment:
      # Defaults in case they are missing in .env
      GOOGLE_APPLICATION_CREDENTIALS: /app/recreacion_linux/credentials.json
      INTER_MAP_PATH: /app/recreacion_linux/interrapidisimo_traking_map.json
      HEADLESS: "true"
      DEBUG_SCRAPER: "false"
      BLOCK_RESOURCES: "true"
      SLOW_MO: "100"
      TIMEOUT_MS: "120000"
      PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS: "1"
      TZ: America/Bogota
    # Mount only what is needed (avoid bind-mounting whole repo in prod)
    volumes:
      - ./out:/app/recreacion_linux/out
      - ./logs:/app/recreacion_linux/logs
      - ./traces:/app/recreacion_linux/traces
      - ./credentials.json:/app/recreacion_linux/credentials.json:ro
      - ./interrapidisimo_traking_map.json:/app/recreacion_linux/interrapidisimo_traking_map.json:ro
    # Always execute as a module so imports resolve (recreacion_linux.*)
    command: ["bash","-lc","python -m recreacion_linux.main --help"]
